// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edyzsxmttwuiwytlaoxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkeXpzeG10dHd1aXd5dGxhb3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5ODIzODAsImV4cCI6MjA1NTU1ODM4MH0.zJ220ldGafAwzfIpnhep8rFJveOFyTlktaVpsWBlzCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);